import turtle

turtle.setup(900, 900)

wn = turtle.Screen()

wn.bgcolor("white")

nem = turtle.Turtle()

nem.shape("turtle")

nem.speed("fastest")

def drawA():
    nem.color("white")
    nem.forward(10)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(20)
    nem.right(90)
    nem.forward(50)
    nem.backward(30)
    nem.right(90)
    nem.forward(20)
    nem.backward(20)
    nem.left(90)
    nem.forward(30)
    nem.left(90)

def drawB():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(135)
    nem.forward(17.6775)
    nem.right(90)
    nem.forward(17.6775)
    nem.left(90)
    nem.forward(17.6775)
    nem.right(90)
    nem.forward(17.6775)
    nem.left(135)
    nem.color("white")
    nem.forward(10)
    

def drawC():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(30)
    nem.right(180)
    nem.forward(30)
    nem.left(90)
    nem.forward(50)
    nem.left(90)
    nem.forward(30)

def drawD():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(135)
    nem.forward(35.355)
    nem.right(90)
    nem.forward(35.355)
    nem.left(135)
    nem.color("white")
    nem.forward(15)

def drawE():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(20)
    nem.backward(20)
    nem.right(90)
    nem.forward(25)
    nem.left(90)
    nem.forward(20)
    nem.backward(20)
    nem.right(90)
    nem.forward(25)
    nem.left(90)
    nem.forward(20)
    nem.color("white")
    
def drawF():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(20)
    nem.backward(20)
    nem.right(90)
    nem.forward(25)
    nem.left(90)
    nem.forward(20)
    nem.backward(20)
    nem.right(90)
    nem.forward(25)
    nem.left(90)
    nem.color("white")
    nem.forward(20)

def drawL():
    nem.color("white")
    nem.forward(20)
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.backward(50)
    nem.right(90)
    nem.forward(20)
    nem.color("white")
    nem.forward(10)
    nem.color("black")

def drawO():
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(30)
    nem.right(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(30)
    nem.backward(30)
    nem.right(180)
    nem.color("white")
    nem.forward(10)

def drawR():
    nem.color("black")
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.forward(25)
    nem.right(90)
    nem.forward(25)
    nem.right(90)
    nem.forward(25)
    nem.left(135)
    nem.forward(35.355)
    nem.left(45)
    nem.color("white")
    nem.forward(10)


def drawZ():
    nem.color("white")
    nem.forward(10)
    nem.left(90)
    nem.forward(50)
    nem.right(90)
    nem.color("black")
    nem.forward(25)
    nem.right(116.6)
    nem.forward(55.9)
    nem.left(116.6)
    nem.forward(25)
    nem.left(45)
    nem.color("white")
    nem.forward(10)
    

drawA()
drawB()
drawC()
drawD()
drawE()
drawF()
drawL()
drawO()
drawR()
drawZ()
